---
- name: make config directories
  file:
    name: "/srv/{{ item }}"
    state: directory
    recurse: yes
    mode: "0777"
  loop:
    - alertmanager
    - alertmanager/data
  tags:
    - monitor

- name: Configure Alertmanager
  template:
    src: alertmanager/alertmanager.yml.j2
    dest: /srv/alertmanager/alertmanager.yml
  tags:
    - monitor
    - alert

- name: Install Alertmanager
  docker_container:
    name: alertmanager
    image: quay.io/prometheus/alertmanager
    restart_policy: unless-stopped
    restart: true
    timeout: 120
    recreate: true
    mounts:
    - type=bind
      target=/etc/alertmanager/alertmanager.yml
      source=/srv/alertmanager/alertmanager.yml
    - type=bind
      target=/alertmanager
      source=/srv/alertmanager/data
    command: "--config.file=/etc/alertmanager/alertmanager.yml"
    networks:
      name=monitoring
  tags:
    - monitor
    - alert
