---
all:
  children:
    servers:
      children:
        local:
          children:
            ubuntu:
              children:
                application:
                  hosts:
                    app-server:
                      ansible_host: 54.144.244.50
                      ansible_user :  ubuntu
                database:
                  hosts:
                    db-server:
                      ansible_host: 18.234.88.130
                      ansible_port :  2200
                      ansible_user :  ubuntu
                      private_key_file :  ../Capstone_keypair.pem
                      ansible_ssh_common_args: |
                        '
                        -o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ../Capstone_keypair.pem -o \'ForwardAgent yes\' ubuntu@3.90.11.111 -p 2200 -W %h:%p"
                        '
                # bastion:
                #   hosts:
                #     bastion-server:
                #       ansible_host: 3.90.11.111
                #       ansible_user :  ubuntu
                monitoring:
                  hosts:
                    monitoring-server:
                      ansible_host: 44.203.55.152
                      ansible_user :  ubuntu
 