---
all:
  children:
    servers:
      children:
        local:
          children:
            ubuntu:
              children:
                application:
                  hosts:
                    app-server-1:
                      ansible_host: 52.56.180.209
                      ansible_user :  ubuntu
                      ansible_ssh_common_args: '-o IdentityFile=capstone-test-key.pem -o StrictHostKeyChecking=no'

                    app-server-2:
                      ansible_host: 13.41.227.172
                      ansible_user :  ubuntu
                      ansible_ssh_common_args: '-o IdentityFile=capstone-test-key.pem -o StrictHostKeyChecking=no'

                database:
                  hosts:
                    db-server:
                      ansible_host: 10.0.3.134
                      ansible_user :  ubuntu
                      ansible_port :  2200
                      ansible_ssh_common_args: '-o IdentityFile=capstone-test-key.pem -o StrictHostKeyChecking=no -o ProxyCommand="ssh -i capstone-test-key.pem ubuntu@3.9.13.54 -p 2200 -W %h:%p"'

                bastion:
                  hosts:
                    bastion-server:
                      ansible_host: 3.9.13.54
                      ansible_user :  ubuntu
                      ansible_port: 2200
                      ansible_ssh_common_args: '-o IdentityFile=capstone-test-key.pem -o StrictHostKeyChecking=no'

                monitoring:
                  hosts:
                    monitoring-server:
                      ansible_host: 18.132.41.217
                      ansible_user :  ubuntu
                      ansible_ssh_common_args: '-o IdentityFile=capstone-test-key.pem -o StrictHostKeyChecking=no'
