---
ansible_become: True
ansible_user: ubuntu
ansible_password:
ansible_become_password:
# Node exporter version to install
node_exporter_version: "1.4.0"
# URL and Creds for loki
lokiapi: "loki.monitoring.de-marauder.me"

prometheus_cert_file: "/srv/prometheus/certificate.key"
prometheus_key_file: "/srv/prometheus/keyfile.pem"
htaccessusr: "monitor"
htaccesspwd: "monitor-password"

timezone: "Africa/Lagos"

certbot_app_1_site_names:  
  - "node.app-1.de-marauder.me"
  - "docker.app-1.de-marauder.me"
  - "cadvisor.app-1.de-marauder.me"
certbot_app_2_site_names:  
  - "node.app-2.de-marauder.me"
  - "docker.app-2.de-marauder.me"
  - "cadvisor.app-2.de-marauder.me"

certbot_site_names:  
  - "grafana.monitoring.de-marauder.me"
  - "prom.monitoring.de-marauder.me"
  - "loki.monitoring.de-marauder.me"
  - "node.monitoring.de-marauder.me"
  - "cadvisor.monitoring.de-marauder.me"
  - "docker.monitoring.de-marauder.me"
  - "alert.monitoring.de-marauder.me"

certbot_db_site_names:
  - "db.de-marauder.me"
  - "node.db.de-marauder.me"
  - "docker.db.de-marauder.me"
  - "cadvisor.db.de-marauder.me"

certbot_package: "python3-certbot-nginx"
certbot_plugin: "nginx"
certbot_mail_address: chiezike16@gmail.com

db_user: root
db_password: root
db_ip: 10.0.3.7

smtp_username: chiezike16
smtp_password: jmcxjnoteyvppwcs
slack_webhook: https://hooks.slack.com/services/SLACK_WEBHOOK